import { Inter } from "next/font/google";
import "./globals.css";
import prisma from "@/prisma";
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ryan",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const pages=await prisma.post.findMany({
    where:{
      kind:{
        equals:"page"
      }
    }
  })
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Link href='/'>博客</Link>
          {
            pages.map(page=>{
              return <Link key={page.id} href={`/post/${page.id}`}>{page.title}</Link>
            })
          }
          <Link href='/admin/post/list'>后台</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
