import { Inter } from "next/font/google";
import "./globals.css";
import prisma from "@/prisma";
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ryan",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const pages = await prisma.post.findMany({
    where: {
      kind: {
        equals: "page"
      }
    }
  })
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <div className="nav">
            <div className="menu">
              <Link href='/'>博客</Link>
              {
                pages.map(page => {
                  return <Link key={page.id} href={`/post/${page.id}`}>{page.title}</Link>
                })
              }
            </div>
            <div>
              <Link href='/admin/post/list'>后台</Link>
            </div>
          </div>
          {children}
          <div style={{ textAlign: 'center' }}>Copyright 2019-{new Date().getFullYear()} ryan 版权所有 保留所有权利</div>
        </div>
      </body>
    </html>
  );
}
