import { Inter } from "next/font/google";
import prisma from "@/prisma";
import Link from "next/link";
import "../tailwind/tailwind.css";

export const metadata = {
  title: "ryan",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const pages = await prisma.post.findMany({
    where: {
      kind: {
        equals: "page",
      },
    },
  });
  const changeMode = () => {};
  return (
    <html lang="en">
      <body>
        <div className="container mx-auto bg-white">
          <div className="flex justify-between items-center leading-10 text-blue-600">
            <div className="flex gap-3">
              <div>
                <Link href="/">博客</Link>
              </div>
              {pages.map((page) => {
                return (
                  <div key={page.id}>
                    <Link href={`/post/${page.id}`}>{page.title}</Link>
                  </div>
                );
              })}
            </div>
            <div>
              <Link href="/admin/post/list">后台</Link>
            </div>
          </div>
          <div className="relative">{children}</div>
          <div className="text-center">
            Copyright 2019-{new Date().getFullYear()} ryan 版权所有 保留所有权利
          </div>
        </div>
      </body>
    </html>
  );
}
