import Link from "../components/link";
import "../tailwind/tailwind.css";
export const metadata = {
  title: "ryan",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div className="w-40 text-center pt-4">
            <div className="leading-7">
              <Link href="/">回主页</Link>
            </div>
            <div className="leading-7">
              <Link href="/admin/post/list">博文管理</Link>
            </div>
            <div className="leading-7">
              <Link href="/admin/imgs/list">图床管理</Link>
            </div>
          </div>
          <div className="flex-1 pt-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
