import styles from './layout.module.css'
import Link from '../components/link';
import './globals.css'
export const metadata = {
  title: "ryan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={styles.admin}>
          <div className={styles.menuList}>
            <div>
              <Link href='/'>回主页</Link>
            </div>
            <div>
              <Link href="/admin/post/list">博文管理</Link>
            </div>
            <div>
              <Link href="/admin/imgs/list">图床管理</Link>
            </div>
          </div>
          <div style={{ flex: 1 }}>
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
