import Nav from "../components/nav";
import "../globals.css";
export const metadata = {
  title: "ryan",
  description: "Generated by create next app",
};
const menuItems = [
  {
    href: "/",
    title: "首页",
  },
  {
    href: "/admin/post/list",
    title: "博客管理",
  },
  {
    href: "/admin/imgs/list",
    title: "图床管理",
  },
];
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div className="px-2 pt-2">
            <Nav menuItems={menuItems} orientation="vertical"></Nav>
          </div>
          <div className="flex-1 pt-2">{children}</div>
        </div>
      </body>
    </html>
  );
}
